server.port=${PORT:8080}
logging.level.org.atmosphere = warn
spring.mustache.check-template-location = false

# Launch the default browser when starting the application in development mode
# vaadin.launch-browser=true


# c:\keycloak-26.2.4_db\bin\kc start-dev --http-port=8081

spring.security.oauth2.client.registration.keycloak.client-id=hilla
spring.security.oauth2.client.registration.keycloak.client-secret=0X4xRC6Lc8izC6j8kZ9zPT95OIwtAmYB
spring.security.oauth2.client.registration.keycloak.scope=openid
spring.security.oauth2.client.registration.keycloak.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.keycloak.redirectUri=http://localhost:8080/login/oauth2/code/keycloak


spring.security.oauth2.client.provider.keycloak.issuer-uri=http://localhost:8081/realms/vaadin

spring.security.oauth2.client.provider.keycloak.user-name-attribute=preferred_username

spring.datasource.url=jdbc:postgresql://localhost:5432/keycloak_app
spring.datasource.username=keycloak
spring.datasource.password=keycloak
spring.jpa.hibernate.ddl-auto=create-drop
#spring.jpa.show-sql=true
# Enable Virtual Threads
spring.threads.virtual.enabled=true

server.servlet.session.cookie.max-age=2m
server.servlet.session.timeout=2m