# spring.config.import=file:/opt/casn-admin/application.properties
# spring.config.import=file:/home/bana/app/app3/application.properties

server.port=${PORT:8080}
logging.level.org.atmosphere = warn
spring.mustache.check-template-location = false

vaadin.launch-browser=false
# spring.datasource.url = jdbc:postgresql://192.168.83.139:5432/vaadinstart
# spring.datasource.username = vaadinstart
# spring.datasource.password = vaadinstart
# spring.jpa.hibernate.ddl-auto = none
vaadin.allowed-packages = com.vaadin,org.vaadin,com.flowingcode,com.example.application
spring.jpa.defer-datasource-initialization = true

# server.servlet.context-path=/hilla

spring.security.oauth2.client.registration.keycloak.client-id=hilla
spring.security.oauth2.client.registration.keycloak.client-secret=X9AevDivEnNbVh8YTib1Lg7tawKF8ic9tHtFOMhQNUQxPRnQirNFgTzt6XaA8P0fJv6H7ghwjBknJIpunf3tEs
spring.security.oauth2.client.registration.keycloak.scope=openid
spring.security.oauth2.client.registration.keycloak.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.keycloak.redirectUri=http://localhost:8080/login/oauth2/code/keycloak


spring.security.oauth2.client.provider.keycloak.issuer-uri=http://localhost:8081/realms/vaadin

spring.security.oauth2.client.provider.keycloak.user-name-attribute=preferred_username
